//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JourneyTowardsDreamzEntities : DbContext
    {
        public JourneyTowardsDreamzEntities()
            : base("name=JourneyTowardsDreamzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryMaster> CategoryMasters { get; set; }
        public virtual DbSet<Consumer> Consumers { get; set; }
        public virtual DbSet<IndustryMaster> IndustryMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<SubscriptionMaster> SubscriptionMasters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VideoTransaction> VideoTransactions { get; set; }
        public virtual DbSet<ApplicationTracker> ApplicationTrackers { get; set; }
    }
}
