//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoTransaction
    {
        public int VideoId { get; set; }
        public string VideoName { get; set; }
        public int UserId { get; set; }
        public int CategoryId { get; set; }
        public string StoragePath { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual User User { get; set; }
    }
}
